<a href="https://colab.research.google.com/github/tkd8973/ML_Project/blob/main/ML/MP2_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:

Jan_data = pd.read_csv('https://github.com/jaiwon880/ML_Projiect/raw/main/Data/%EC%95%84%ED%8C%8C%ED%8A%B8_%EB%A7%A4%EB%A7%A4__%EC%8B%A4%EA%B1%B0%EB%9E%98%EA%B0%80_20230321134107_1%EC%9B%94.csv')
Feb_Data = pd.read_csv('https://raw.githubusercontent.com/jaiwon880/ML_Projiect/main/Data/%EC%95%84%ED%8C%8C%ED%8A%B8_%EB%A7%A4%EB%A7%A4__%EC%8B%A4%EA%B1%B0%EB%9E%98%EA%B0%80_20230321134120_2%EC%9B%94.csv')

def Pre(datas):
    data=[]
    # datas['거래금액(만원)'].str.strip().apply(lambda x: x.replace(',',''))
    
    datas['거래금액(만원)']=(datas['거래금액(만원)'].str.replace(',','')).str.strip().astype(int)
    datas["평당가"] = (datas["거래금액(만원)"] / datas["전용면적(㎡)"]*0.3025) # 평당가 계산하여 새로운 컬럼 추가
    aa=datas['계약년월'].astype(str)
    bb=datas['계약일'].astype(str)
    datas['date'] = aa+bb
    datas['date'] = pd.to_datetime(datas['date'], format='%Y%m%d')
    datas['금리'] = datas.apply(lambda x: 3.25 if ((x['계약년월']== 202301) & (x['계약일'] < 13)) else 3.5, axis=1)
    datas.drop(['계약년월','계약일'],axis=1,inplace=True)
    datas['거래유형'] = datas['거래유형'].apply(lambda x:0 if x=='중개거래' else 1)
    datas.dropna(inplace=True)
    data= datas[datas['시군구']=='충청남도 계룡시 금암동']    

    return data
    
df1= Pre(Jan_data)

In [5]:

df2 = Pre(Feb_Data)

In [6]:
df2

,시군구,전용면적(㎡),거래금액(만원),건축년도,거래유형,평당가,date,금리
28585,충청남도 계룡시 금암동,84.9600,22300,2005.0,0,79.399129,2023-02-05,3.5
28586,충청남도 계룡시 금암동,59.9700,15300,2005.0,0,77.176088,2023-02-07,3.5
28587,충청남도 계룡시 금암동,84.9600,22650,2005.0,0,80.645304,2023-02-11,3.5
28588,충청남도 계룡시 금암동,84.9600,21300,2005.0,0,75.838630,2023-02-13,3.5
28589,충청남도 계룡시 금암동,59.9700,21000,2005.0,0,105.927964,2023-02-24,3.5
28590,충청남도 계룡시 금암동,84.9600,21800,2005.0,0,77.618879,2023-02-28,3.5
28591,충청남도 계룡시 금암동,84.8600,26000,2005.0,0,92.682065,2023-02-04,3.5
28592,충청남도 계룡시 금암동,84.8600,17900,2005.0,0,63.808037,2023-02-21,3.5
28593,충청남도 계룡시 금암동,123.6361,30500,2005.0,0,74.624240,2023-02-04,3.5
28594,충청남도 계룡시 금암동,84.9769,19200,2005.0,0,68.347986,2023-02-18,3.5
28595,충청남도 계룡시 금암동,84.9769,20000,2005.0,0,71.195819,2023-02-18,3.5

In [7]:
df1

,시군구,전용면적(㎡),거래금액(만원),건축년도,거래유형,평당가,date,금리
17807,충청남도 계룡시 금암동,59.9700,15500,2005.0,0,78.184926,2023-01-02,3.25
17808,충청남도 계룡시 금암동,118.1200,29000,2005.0,0,74.267694,2023-01-14,3.50
17809,충청남도 계룡시 금암동,59.9700,14000,2005.0,0,70.618643,2023-01-17,3.50
17810,충청남도 계룡시 금암동,84.9600,24000,2005.0,0,85.451977,2023-01-31,3.50
17811,충청남도 계룡시 금암동,84.8600,22000,2005.0,1,78.423285,2023-01-12,3.25
17812,충청남도 계룡시 금암동,84.8600,20200,2005.0,0,72.006835,2023-01-18,3.50
17813,충청남도 계룡시 금암동,84.8600,21000,2005.0,0,74.858591,2023-01-29,3.50
17814,충청남도 계룡시 금암동,123.6361,30000,2005.0,0,73.400892,2023-01-03,3.25
17815,충청남도 계룡시 금암동,84.9769,18000,2005.0,0,64.076237,2023-01-20,3.50

In [8]:
df1.sort_values('date',inplace=True)
df2.sort_values('date',inplace=True)

<ipython-input-8-352f1af1da0b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.sort_values('date',inplace=True)
<ipython-input-8-352f1af1da0b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.sort_values('date',inplace=True)

In [9]:
df1

,시군구,전용면적(㎡),거래금액(만원),건축년도,거래유형,평당가,date,금리
17807,충청남도 계룡시 금암동,59.9700,15500,2005.0,0,78.184926,2023-01-02,3.25
17814,충청남도 계룡시 금암동,123.6361,30000,2005.0,0,73.400892,2023-01-03,3.25
17811,충청남도 계룡시 금암동,84.8600,22000,2005.0,1,78.423285,2023-01-12,3.25
17808,충청남도 계룡시 금암동,118.1200,29000,2005.0,0,74.267694,2023-01-14,3.50
17809,충청남도 계룡시 금암동,59.9700,14000,2005.0,0,70.618643,2023-01-17,3.50
17812,충청남도 계룡시 금암동,84.8600,20200,2005.0,0,72.006835,2023-01-18,3.50
17815,충청남도 계룡시 금암동,84.9769,18000,2005.0,0,64.076237,2023-01-20,3.50
17813,충청남도 계룡시 금암동,84.8600,21000,2005.0,0,74.858591,2023-01-29,3.50
17810,충청남도 계룡시 금암동,84.9600,24000,2005.0,0,85.451977,2023-01-31,3.50

In [10]:
df2

,시군구,전용면적(㎡),거래금액(만원),건축년도,거래유형,평당가,date,금리
28591,충청남도 계룡시 금암동,84.8600,26000,2005.0,0,92.682065,2023-02-04,3.5
28593,충청남도 계룡시 금암동,123.6361,30500,2005.0,0,74.624240,2023-02-04,3.5
28585,충청남도 계룡시 금암동,84.9600,22300,2005.0,0,79.399129,2023-02-05,3.5
28586,충청남도 계룡시 금암동,59.9700,15300,2005.0,0,77.176088,2023-02-07,3.5
28587,충청남도 계룡시 금암동,84.9600,22650,2005.0,0,80.645304,2023-02-11,3.5
28588,충청남도 계룡시 금암동,84.9600,21300,2005.0,0,75.838630,2023-02-13,3.5
28594,충청남도 계룡시 금암동,84.9769,19200,2005.0,0,68.347986,2023-02-18,3.5
28595,충청남도 계룡시 금암동,84.9769,20000,2005.0,0,71.195819,2023-02-18,3.5
28592,충청남도 계룡시 금암동,84.8600,17900,2005.0,0,63.808037,2023-02-21,3.5
28589,충청남도 계룡시 금암동,59.9700,21000,2005.0,0,105.927964,2023-02-24,3.5
28590,충청남도 계룡시 금암동,84.9600,21800,2005.0,0,77.618879,2023-02-28,3.5

In [11]:
df1.set_index('date',inplace=True)

In [12]:
df1

                     시군구   전용면적(㎡)  거래금액(만원)    건축년도  거래유형        평당가    금리
date
2023-01-02  충청남도 계룡시 금암동   59.9700     15500  2005.0     0  78.184926  3.25
2023-01-03  충청남도 계룡시 금암동  123.6361     30000  2005.0     0  73.400892  3.25
2023-01-12  충청남도 계룡시 금암동   84.8600     22000  2005.0     1  78.423285  3.25
2023-01-14  충청남도 계룡시 금암동  118.1200     29000  2005.0     0  74.267694  3.50
2023-01-17  충청남도 계룡시 금암동   59.9700     14000  2005.0     0  70.618643  3.50
2023-01-18  충청남도 계룡시 금암동   84.8600     20200  2005.0     0  72.006835  3.50
2023-01-20  충청남도 계룡시 금암동   84.9769     18000  2005.0     0  64.076237  3.50
2023-01-29  충청남도 계룡시 금암동   84.8600     21000  2005.0     0  74.858591  3.50
2023-01-31  충청남도 계룡시 금암동   84.9600     24000  2005.0     0  85.451977  3.50

In [13]:
df2.set_index('date',inplace=True)

In [14]:
df2

                     시군구   전용면적(㎡)  거래금액(만원)    건축년도  거래유형         평당가   금리
date
2023-02-04  충청남도 계룡시 금암동   84.8600     26000  2005.0     0   92.682065  3.5
2023-02-04  충청남도 계룡시 금암동  123.6361     30500  2005.0     0   74.624240  3.5
2023-02-05  충청남도 계룡시 금암동   84.9600     22300  2005.0     0   79.399129  3.5
2023-02-07  충청남도 계룡시 금암동   59.9700     15300  2005.0     0   77.176088  3.5
2023-02-11  충청남도 계룡시 금암동   84.9600     22650  2005.0     0   80.645304  3.5
2023-02-13  충청남도 계룡시 금암동   84.9600     21300  2005.0     0   75.838630  3.5
2023-02-18  충청남도 계룡시 금암동   84.9769     19200  2005.0     0   68.347986  3.5
2023-02-18  충청남도 계룡시 금암동   84.9769     20000  2005.0     0   71.195819  3.5
2023-02-21  충청남도 계룡시 금암동   84.8600     17900  2005.0     0   63.808037  3.5
2023-02-24  충청남도 계룡시 금암동   59.9700     21000  2005.0     0  105.927964  3.5
2023-02-28  충청남도 계룡시 금암동   84.9600     21800  2005.0     0   77.618879  3.5

In [15]:
df1.drop('시군구',axis=1,inplace=True)
df2.drop('시군구',axis=1,inplace=True)

<ipython-input-15-7b5d665852e7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop('시군구',axis=1,inplace=True)
<ipython-input-15-7b5d665852e7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('시군구',axis=1,inplace=True)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

train = df1
test = df2
X_train = train.drop('거래금액(만원)',axis=1)
y_train = train['거래금액(만원)']
X_test = test.drop('거래금액(만원)',axis=1)
y_test = test['거래금액(만원)']

In [17]:
#@title KNN
from sklearn.metrics import mean_squared_error
models = []
for i in range(0,len(df1)):
    if i==0:
        continue
    model = KNeighborsRegressor(n_neighbors=i,weights='distance')
    model.fit(X_train,y_train)

    pred=model.predict(X_test)
    rmse = mean_squared_error(y_test,pred)**0.5
    
    models.append(rmse)

In [18]:
models

[1814.9004480586907,
 978.8189415294619,
 1401.3754303842604,
 1369.0983699588016,
 1486.5943520530018,
 1657.352431802638,
 1845.1453783497445,
 1676.1488927773141]

In [20]:
model = KNeighborsRegressor(n_neighbors=3,weights='distance')
model.fit(X_train,y_train)
dt_test = pd.DataFrame(np.array([86,2005,0,85,3.75]).reshape(1,-1),columns=X_train.columns)
aa=model.predict(dt_test)

aa

array([23467.52457446])